### ISSUE TITLE
印章识别模型训练时，数据标签格式问题？

### ISSUE THREAD

**Issue by htaoruan** [Gmgge/TrOCR-Seal-Recognition#1]
非常感谢您的分享，我想请教下模型训练时，印章图像对应的标注，直接是整个印章图像和对应的标签吗？印章上是弯曲文本区域，而且会有多个，是当成多行问题解决吗？还是说需要对弯曲文本区域进行多边形标注，再做处理？

**Comment by Gmgge** [comment]
你好，根据我的实验，基于transformer的trocr，parseq算法，都具有潜在的多行识别能力。

**Comment by papersuper** [comment]
非常感谢楼主的分享，请问可以提供一下具体的数据集格式吗，可以提供一下数据标注的具体工具吗

**Comment by papersuper** [comment]
非常感谢楼主的分享，请问运行onnx模型时出现了这个问题是什么原因呢
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(int32)) , expected: (tensor(int64))

**Comment by Gmgge** [comment]
@papersuper 很抱歉没有看到，你需要reopen这个问题或者提出新问题我才能第一时间看到这个消息。

**数据集格式：**
0.png  # 图像
0.txt # 标签
标签内容 南京谐诚机电工程有限公司#审计章 其中#作为换行符的替代

**运行报错**
看样子是数据格式不匹配，能进一步提供报错信息吗？或者你已经解决了问题，欢迎提pr

**Comment by Gmgge** [comment]
我 更新了推理代码，应该修复了该问题，你可以尝试下最新的代码
