### ISSUE TITLE
印章模型无法识别数字

### ISSUE THREAD

**Issue by whiteless9** [Gmgge/TrOCR-Seal-Recognition#11]
如题，目前印章识别无法识别数字，字典里面也有相关数字字符，是需要加相关字符数据集进行微调模型吗？
![Uploading Snipaste_2024-01-02_17-55-12.png…]()

**Comment by Gmgge** [comment]
你的图片没有上传成功，这边无法查看到具体情况，建议重新上传下。

如果是印章编号的话，当前由于互联网采集的印章数据清晰度不够，我放弃了对印章编号的识别，不过无论哪种情况都可以收集相关数据集按照流程进行微调，根据训练经验来说，很快就会收敛。

**Comment by whiteless9** [comment]
![Snipaste_2024-01-02_17-55-12](https://github.com/Gmgge/TrOCR-Seal-Recognition/assets/52316271/f0ca5f1a-b1ea-4ba7-97f8-7e93ecdc82a3)
了解  就是最下环的文字

**Comment by whiteless9** [comment]
是的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 四月是你的讠荒言 ***@***.***&gt;
发送时间: 2025年1月14日 15:34
收件人: Gmgge/TrOCR-Seal-Recognition ***@***.***&gt;
抄送: whiteless9 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Gmgge/TrOCR-Seal-Recognition] 印章模型无法识别数字 (Issue #11)

**Comment by AlieinApril** [comment]
谢谢，你有训练好的能识别印章编号的模型么？自己在标一遍，太累了
