### ISSUE TITLE
印章数据

### ISSUE THREAD

**Issue by yqj0919** [Gmgge/TrOCR-Seal-Recognition#12]
印章数据怎么给你呢？

**Comment by Gmgge** [comment]
我最近将要构建印章数据页面，每个想要共享的人都可以把链接分享在该页面中，并且可以直观的看到大家的贡献。

基于如此，我将在未来首先会持续公开真实印章与生成的印章数据，以共同推动该方向的发展。

**Comment by wibin86** [comment]
https://rrc.cvc.uab.es/?ch=20&com=introduction
这是印个印章检测是识别的比赛，里面提供了印章数据，可以用来训练和验证

**Comment by Gmgge** [comment]
很感谢你提供的信息，我未能打开你发的链接，是华中科大组织的印章识别吗？

**Comment by wibin86** [comment]
嗯嗯，是的，华中科大组织的，可能需要梯子吧
