### ISSUE TITLE
app.py 没有找到，能否补档百度网盘链接

### ISSUE THREAD

**Issue by Super-six-java** [Gmgge/TrOCR-Seal-Recognition#17]
大佬，我在trocr_chinese中找到了模型以及app.py,使用

python -m transformers.onnx -m ./torchmode --feature=vision2seq-lm onnx-modlepath --atol 1e-4 转换了onnx模型
但是转换结果精确的不太行，不能达到你在线部署的那个识别率

**Comment by Gmgge** [comment]
你好，已补档永久链接模型。
在线部署模型为二次优化模型，将在近期进一步优化之后开源。

**Comment by Super-six-java** [comment]
谢谢大佬😘😍
