### ISSUE TITLE
关于其他任务的预训练模型

### ISSUE THREAD

**Issue by yjmm10** [Gmgge/TrOCR-Seal-Recognition#19]
首先非常感谢您对文档智能的各个模块任务的贡献，针对公式识别以及表格识别模块是否有开源的打算呢

**Comment by Gmgge** [comment]
你好，目前尚在印章识别优化阶段，感兴趣话可以了解[paddle OCR](https://github.com/PaddlePaddle/PaddleOCR)里面相关表格识别

**Comment by yubuyuabc** [comment]
> 你好，目前尚在印章识别优化阶段，将根据进度逐渐推进。 感兴趣话可以了解[paddle OCR](https://github.com/PaddlePaddle/PaddleOCR)里面相关表格识别内容。

 trocr-chinese:latest 请问可以提供一下这个镜像嘛，dockerhub获取不到这个镜像

**Comment by Gmgge** [comment]
由于镜像是参考项目提供的，如果目前获取不到docker镜像的话，可以使用anaconda 构建运行环境。

**Comment by Gmgge** [comment]
@yubuyuabc 你好 不知道你的环境还有问题嘛？这边更新了环境构建的流程
