### ISSUE TITLE
模型和数据集

### ISSUE THREAD

**Issue by LUXUS1** [Gmgge/TrOCR-Seal-Recognition#2]
您好，请问这个印章识别的模型和数据集删除了吗？

**Comment by Gmgge** [comment]
模型：我更新下推理模型的链接，
数据集：由于当前数据集相对较小，为了进一步扩充，当前数据集为共享规则，需要使用者共享出一定的数据集才可以获取所有数据集。

**Comment by LUXUS1** [comment]
> 模型：我更新下推理模型的链接， 数据集：由于当前数据集相对较小，为了进一步扩充，当前数据集为共享规则，需要使用者共享出一定的数据集才可以获取所有数据集。
非常感谢，我现在有1.5k左右的数据，都是自己合成的，请问如何共享？数据如下图所示：
![image](https://github.com/Gmgge/TrOCR-Seal-Recognition/assets/57226206/888e1d5b-23f7-44b8-a47e-4f5324e9388c)
