### ISSUE TITLE
缺失源代码，README中的app.py没有找到

### ISSUE THREAD

**Issue by zealinux** [Gmgge/TrOCR-Seal-Recognition#22]

**Comment by huah6571** [comment]
你需要在这个源码的上游 trocr-chinese里面找那个app.py 粘贴过来就能用

**Comment by Gmgge** [comment]
@zealinux 以修复，现在放在tool里面了。 按照[huah6571](https://github.com/huah6571)所说的也可以，可以在readme中找到该项目的参考项目trocr-chinese，即可发现该文件。
