### ISSUE TITLE
有些印章上边写字的不太准啊

### ISSUE THREAD

**Issue by shenjunyuqwert** [Gmgge/TrOCR-Seal-Recognition#27]
![image](https://github.com/Gmgge/TrOCR-Seal-Recognition/assets/59952043/20ffc8cc-b6f4-4ae4-b12f-9e9e8b75d67a)
比如这个检测出来是空的

**Comment by Gmgge** [comment]
![image](https://github.com/Gmgge/TrOCR-Seal-Recognition/assets/48548141/d224475c-f730-463e-9544-c1f819de66d6)
你有尝试过我的体验版模型吗，不过这个版本是自带印章检测的，所以不需要裁剪出来，这个是稍微优化点的版本

**Comment by shenjunyuqwert** [comment]
体验版模型在哪里啊

**Comment by Gmgge** [comment]
我在阿里云部署了http://120.27.143.171:19192/，可以尝试一下。

**Comment by shenjunyuqwert** [comment]
![image](https://github.com/Gmgge/TrOCR-Seal-Recognition/assets/59952043/3868ba25-b548-4ff0-a2ed-be2160abb877)
还是不准啊。

**Comment by shenjunyuqwert** [comment]
![image](https://github.com/Gmgge/TrOCR-Seal-Recognition/assets/59952043/bca57327-0e05-44de-9bb9-0634cf51d340)
我想顺便问下，你训练的时候这共享数据集中的四份数据都用了吗，还是只用了其中部分，还是在分享之外用了更多的

**Comment by Gmgge** [comment]
1.在线部署的增加了印章检测模块，应用场景没有考虑过这种直接裁剪出来的场景，不用裁剪直接把含有印章的图片上传进行识别。
2.数据集是用了更多的。
