### ISSUE TITLE
数据集重复了

### ISSUE THREAD

**Issue by forrestr91** [Gmgge/TrOCR-Seal-Recognition#28]
[【生成】paddlepaddle社区印章数据集1](https://aistudio.baidu.com/datasetdetail/199400)
[【生成】paddlepaddle社区印章数据集2](https://aistudio.baidu.com/datasetdetail/154271)
这两个数据集好像是一样的

**Comment by Gmgge** [comment]
感谢反馈，已经删除重复的链接
