### ISSUE TITLE
看介绍说新上传的链接有320*320的新模型，点开seal链接看还是原来的384*384的模型？另有2W+标注好的印章检测数据，暂没法上传，看如何数据共享方便些

### ISSUE THREAD

**Issue by Jonsun-N** [Gmgge/TrOCR-Seal-Recognition#29]
看介绍说新上传的链接有320*320的新模型，点开seal链接看还是原来的384*384的模型？新的320*320的模型大致有哪些更新呢？
另有2W+标注好的印章检测数据，暂没法上传，看如何数据共享方便些

**Comment by Gmgge** [comment]
简单来说哈，320*320就是降低点计算复杂度，会快一点。

如果是2w+的真实印章数据，可以联系我的邮箱 ypoy66378@163.com

**Comment by ChenCong7375** [comment]
蹲一个数据集 775017899@qq.com
我自己标了一千张左右，都是多行文字印章，但是训练感觉数据不够，后续会分享出来。

**Comment by KyleWang-Hunter** [comment]
> 看介绍说新上传的链接有320_320的新模型，点开seal链接看还是原来的384_384的模型？新的320*320的模型大致有哪些更新呢？ 另有2W+标注好的印章检测数据，暂没法上传，看如何数据共享方便些

能否分享下印章数据，近期在做相关项目，932464020@qq.com

**Comment by Gmgge** [comment]
@ChenCong7375 是多行文字真实印章数据集吗？经过沟通，我这边会在处理完[Jonsun-N](https://github.com/Jonsun-N)数据之后开源出来，如果你有分享的想法，正好在本次优化任务中一同处理。

非常期待你的数据分享，这边对多行印章数据的虚拟生成一直没有达到太好的效果，有意可以联系我的邮箱[ypoy66378@163.com](mailto:ypoy66378@163.com)

**Comment by STEARGAZER** [comment]
@Gmgge 您好，我是一名深度学习初学者，最近在尝试训练这个印章识别模型，我自己获取到了大概500张左右的印章图像，如果我要进行标注使用什么工具进行标注？标注的格式具体是怎样的？2251354955@qq.com

**Comment by Gmgge** [comment]
@STEARGAZER 你好，参考我的数据分享页面中，[互联网爬取自制圆形印章数据集](https://pan.baidu.com/s/113ZZUoEYy6evN8gJVCW3bg?pwd=cV1I)，参考rec 中的 seal_0数据集样式
