### ISSUE TITLE
如何共享数据集？

### ISSUE THREAD

**Issue by LUXUS1** [Gmgge/TrOCR-Seal-Recognition#3]
我现在有1.5k左右的数据，都是自己合成的，请问如何共享？数据如下图所示：
![image](https://github.com/Gmgge/TrOCR-Seal-Recognition/assets/57226206/acc1201c-38df-4cff-a993-f4af20b4ead1)

**Comment by Gmgge** [comment]
很感谢你的想法，关于合成公章我这边生成很多，目前缺少的是真实公章。

还是很感谢你的分享，不知道你这边是否收集了这个[ICDAR 2023 Competition on Reading the Seal Title](https://rrc.cvc.uab.es/?ch=20&com=downloads)比赛的数据集。

至于生成公章，不知道你是否尝试过这个[网站](http://redmi.work/)

**Comment by LUXUS1** [comment]
> 很感谢你的想法，关于合成公章我这边生成很多，目前缺少的是真实公章。
> 
> 还是很感谢你的分享，不知道你这边是否收集了这个[ICDAR 2023 Competition on Reading the Seal Title](https://rrc.cvc.uab.es/?ch=20&com=downloads)比赛的数据集。
> 
> 至于生成公章，不知道你是否尝试过这个[网站](http://redmi.work/)

非常感谢大佬，目前生成公章使用的就是这个[网站](http://redmi.work/)，ICDAR的数据集也有使用。但我在训练的过程中发现TrOCR很容易过拟合，不知道您这边的是怎么解决的？此外，还想问一下您的训练数据量大约有多少？
