### ISSUE TITLE
印章图片中文字标注顺序对训练有影响吗？

### ISSUE THREAD

**Issue by ChenCong7375** [Gmgge/TrOCR-Seal-Recognition#30]
![image](https://github.com/Gmgge/TrOCR-Seal-Recognition/assets/32812662/6d5c0ca1-f5d5-488f-86ff-ebb5b607a957)
标注文档为：
![image](https://github.com/Gmgge/TrOCR-Seal-Recognition/assets/32812662/d047865a-49d5-4541-ad8d-1b2a1f7a268a)

请问需要调整标注文本顺序为从上到下吗？

**Comment by Gmgge** [comment]
从理论上来说需要统一逻辑，最好按照上下顺序来。不过我没有测试过乱序的，我这边是丢弃印章编号的。

**Comment by ChenCong7375** [comment]
ok 我修改一下逻辑
请问作者可以分享标注工具吗

**Comment by Gmgge** [comment]
你好，人工检查的话，我是用的是ppocrlabel
