### ISSUE TITLE
训练数据的格式可以给一个示例吗？

### ISSUE THREAD

**Issue by dhhcj** [Gmgge/TrOCR-Seal-Recognition#31]
虽然提供了一些开源数据集，但是并没有给出训练文件中txt文件的示例格式

**Comment by Gmgge** [comment]
rec 识别数据集中已经给标签，seal_0即可参考，seal_1中的标签在Label.txt中，需要自己处理下。

**Comment by Gmgge** [comment]
非常感谢你的反馈，我更新了readme中的训练描述，请查看是否解决你的疑惑。
