### ISSUE TITLE
请问作者提供的seal预训练模型为onnx形式，似乎不能自己训练吧？

### ISSUE THREAD

**Issue by ChenCong7375** [Gmgge/TrOCR-Seal-Recognition#32]

**Comment by ChenCong7375** [comment]
使用TAL_OCR_CHN应该也可以训练吧

**Comment by Gmgge** [comment]
是的，onnx模型已经是转换为部署模型，非常推荐使用TAL_OCR_CHN作为预训练模型进行训练，经过测试该预训练模型训练出的精度会高一点，话说我也不知道为什么！

**Comment by ChenCong7375** [comment]
> 是的，onnx模型已经是转换为部署模型，非常推荐使用TAL_OCR_CHN作为预训练模型进行训练，经过测试该预训练模型训练出的精度会高一点，话说我也不知道为什么！

作者可以提供一个邮箱吗，我可以分享一个小数据集进行训练测试

**Comment by Gmgge** [comment]
非常感谢你有兴趣分享数据集！ 可以联系我的邮箱ypoy66378@163.com
