### ISSUE TITLE
印章角度转正

### ISSUE THREAD

**Issue by PL2584718785** [Gmgge/TrOCR-Seal-Recognition#33]
您好，大佬 针对旋转/有角度的印章，如何转正呢，有方法推荐么？

**Comment by Gmgge** [comment]
1.如果端到端的话，在数据增强里面加入旋转即可，训练出的模型自然可以识别旋转印章；
2.如果实在想要识别印章旋转情况，可以使用带角度的目标检测，例如[PP-YOLOE-R 高性能旋转框检测模型](https://github.com/PaddlePaddle/PaddleDetection?tab=readme-ov-file#pp-yoloe-r-%E9%AB%98%E6%80%A7%E8%83%BD%E6%97%8B%E8%BD%AC%E6%A1%86%E6%A3%80%E6%B5%8B%E6%A8%A1%E5%9E%8B)

**Comment by PL2584718785** [comment]
> 1.如果端到端的话，在数据增强里面加入旋转即可，训练出的模型自然可以识别旋转印章； 2.如果实在想要识别印章旋转情况，可以使用带角度的目标检测，例如[PP-YOLOE-R 高性能旋转框检测模型](https://github.com/PaddlePaddle/PaddleDetection?tab=readme-ov-file#pp-yoloe-r-%E9%AB%98%E6%80%A7%E8%83%BD%E6%97%8B%E8%BD%AC%E6%A1%86%E6%A3%80%E6%B5%8B%E6%A8%A1%E5%9E%8B)


好的好的，非常感谢您的回复！麻烦再请教下，目前项目工程里面有添加旋转这个数据增强操作吗？

**Comment by Gmgge** [comment]
你可以tool/image_aug的[12行](https://github.com/Gmgge/TrOCR-Seal-Recognition/blob/8082788a69355ae504501a7c709eedd18e56b0af/tool/image_aug.py#L12)看到，包含了旋转的增强。

**Comment by PL2584718785** [comment]
> 你可以tool/image_aug的[12行](https://github.com/Gmgge/TrOCR-Seal-Recognition/blob/8082788a69355ae504501a7c709eedd18e56b0af/tool/image_aug.py#L12)看到，包含了旋转的增强。

好的哈，非常感谢您
