### ISSUE TITLE
模型转onnx

### ISSUE THREAD

**Issue by letmeinplzzzzz** [Gmgge/TrOCR-Seal-Recognition#34]
请问onnx模型要怎么转呢，我使用如下脚本报错`python -m \
    transformers.onnx \
    -m /home/liangsuyin/code/TrOCR-Seal-Recognition/cust-data/weights \
    --feature=vision2seq-lm \
    seal-onnx --atol 1e-4
    `
Hugging Face ONNX Exporter tool: error: argument --feature: invalid choice: 'vision2seq-lm' (choose from 'causal-lm', 'causal-lm-with-past', 'default', 'default-with-past', 'masked-lm', 'question-answering', 'seq2seq-lm', 'seq2seq-lm-with-past', 'sequence-classification', 'token-classification')

**Comment by letmeinplzzzzz** [comment]
更新transformers版本好了，没事了

**Comment by swithmn1** [comment]
你升级的版本是多少 @letmeinplzzzzz
