### ISSUE TITLE
共享数据集和标注API问题

### ISSUE THREAD

**Issue by freebooterish** [Gmgge/TrOCR-Seal-Recognition#36]
您好!
1, 请问使用付费api来打标签这种方式,能分享一下具体方式吗? 
2, 分享一个数据集: 链接: https://pan.baidu.com/s/1iOciAjii82nXNyKrbbXciQ?pwd=q6a7 提取码: q6a7
--来自百度网盘超级会员v8的分享

感谢您的辛勤付出! 🥲

**Comment by Gmgge** [comment]
1.付费api这边 [百度](https://ai.baidu.com/tech/ocr/seal)、[阿里](https://market.aliyun.com/products/57002003/cmapi029878.html)、[合合信息](https://www.textin.com/experience/recognize_stamp)、[腾讯云](https://cloud.tencent.com/document/product/866/45807)都提供印章识别业务，可以使用应用场景中的数据测试，之后购买任一家服务都可以。
2.数据链接这边失效了，如果方便的话，可以发我的邮箱ypoy66378@163.com

**Comment by freebooterish** [comment]
> 1.付费api这边 [百度](https://ai.baidu.com/tech/ocr/seal)、[阿里](https://market.aliyun.com/products/57002003/cmapi029878.html)、[合合信息](https://www.textin.com/experience/recognize_stamp)、[腾讯云](https://cloud.tencent.com/document/product/866/45807)都提供印章识别业务，可以使用应用场景中的数据测试，之后购买任一家服务都可以。 2.数据链接这边失效了，如果方便的话，可以发我的邮箱 [ypoy66378@163.com](mailto:ypoy66378@163.com)

好的,已发!
