### ISSUE TITLE
有没有检测模型呀哥哥，么么哒

### ISSUE THREAD

**Issue by Anwang2020** [Gmgge/TrOCR-Seal-Recognition#43]
有没有检测模型呀哥哥，么么哒
有检测的数据集 但是我没有找到，检测的代码在哪里，只找到了对抠出来的印章进行识别的代码

**Comment by KyleWang-Hunter** [comment]
> 近期各种各种琐事耽搁，加上服务器问题，开源的工作进度可能有点缓慢，不过未来应该会有一些空闲的时间来继续相关的工作，敬请期待。

如果这样的话，请问能否先把数据集共享出来呢，让有需要的兄弟自行打标、训练。

**Comment by Gmgge** [comment]
@KyleWang-Hunter 已经开放的数据有个5000张未标注的，你这边是否已经标注了呢？非常期待你的标签贡献，如果可以贡献的话，我会在近期更新中添加贡献说明，并进一步分享出未标注数据。

关于数据的推进是：
1.我首先开发部分真实数据以及标签；
2.开放部分未标注数据，等待其他有需要的小伙伴贡献标签，完成该部分数据数据集，将整理开源给所有小伙伴；
3.循环2步骤，直至所有数据完成标注，至此所有数据也完成了标注、数据集整理、开源等工作。
