### ISSUE TITLE
关于两个模型文件如何在C++部署的问题

### ISSUE THREAD

**Issue by Akiramex** [Gmgge/TrOCR-Seal-Recognition#45]
大佬你好，我是一个深度学习方面的新手。
我在py环境下成功跑通了该项目。
所以我想把本项目的onnx_test.py部署到C++上面。
但是我发现本项目用到的模型有两个encoder_model.onnx和decoder_model.onnx。这和我在网上搜到的C++部署教程不太一致。

请问大佬有什么参考的方向或者指导吗？非常感谢

**Comment by Gmgge** [comment]
参考 onnxruntime 的 cpp demo 进行构建，非常建议多问问大模型，把预处理以及一些操作转换为cpp版本即可，这边想要咨询下，你看中cpp版本的哪个优点了呢？

**Comment by Akiramex** [comment]
最近刚接触这方面的内容，之前做的是C++，只是单纯对C++比较了解而已。对各个版本的优劣我其实没什么太大的感知，见笑了

**Comment by Gmgge** [comment]
或许可以参考一下paddleocr的cpp版本呢，我这边暂时也没有转cpp的经验，非常期待你在这方面有所突破，cpp版本应该速度上会更快点。

**Comment by linglongxian** [comment]
@Akiramex hello，请问你这边实现了c++版本的部署了吗？

**Comment by Akiramex** [comment]
> @Akiramex hello，请问你这边实现了c++版本的部署了吗？

抱歉。暂时把这个想法搁置了

**Comment by linglongxian** [comment]
@Akiramex hello，还有用c++进行部署的想法吗？我这两天写了一个代码，能够输出了（输出结果是对的），但是相比python版本输出不全，如果有的话，咱们一起研究一下，longxian0505@163.com
