### ISSUE TITLE
老师 请问onnx模型在哪下载

### ISSUE THREAD

**Issue by kkiskkk** [Gmgge/TrOCR-Seal-Recognition#47]
下载onnx推理模型，放入当前目录
python onnx_test.py --model {模型目录} --test_img ./img/seal_0.png

## output: '[1.0, 1.0, 1.0, 0.94803417, 0.99987036, 0.9999962, 0.99990654, 1.0, 0.9999809, 0.99999815, 1.0, 1.0, 1.0]
0.99598354
南京谐诚机电工程有限公司

这部分
'

**Comment by Gmgge** [comment]
你好 在该链接 https://pan.baidu.com/s/1yl9bsae7w-lqS4t6Mzh_Qg?pwd=cV1I
