### ISSUE TITLE
如何去除印章背景文字

### ISSUE THREAD

**Issue by wangjiannan98** [Gmgge/TrOCR-Seal-Recognition#49]
请教一下老师，有些图片背景文字干扰特别严重，有哪些方法可以去除掉背景文字吗？我尝试了色度分离，但是在不清晰的图像上，效果很差。

**Comment by Gmgge** [comment]
如果是用端到端方法不用特别在意背景干扰，可以在训练的时候做下背景干扰的数据增强。
