### ISSUE TITLE
识别包含印章的图

### ISSUE THREAD

**Issue by liusssyang** [Gmgge/TrOCR-Seal-Recognition#53]
输入合同文件，希望能够得到印章上的字，我发现使用预训练seal处理效果很差，但在测试时把印章截下传入模型会有效果。针对上述情况，作者可以给俺一些建议吗？

**Comment by Gmgge** [comment]
该项目是印章图像端到端识别模型，如果输入包含印章的图像，首先需要进行印章检测，检测到印章的区域之后再使用该模型进行识别即可。

**Comment by liusssyang** [comment]
嗯嗯，谢谢回复！
