### ISSUE TITLE
推理完全不对

### ISSUE THREAD

**Issue by Adorablepet** [Gmgge/TrOCR-Seal-Recognition#56]
使用自己标注的数据6000张，paddle合成10000张，以及网友贡献的4000张。利用现有的超参数训练。这是输出日志。是不是哪里有问题。
[trainer_state.json](https://github.com/user-attachments/files/18019150/trainer_state.json)

**Comment by Adorablepet** [comment]
`aug_seq = sometimes(iaa.Sequential([
    iaa.LinearContrast((0.9, 1.1)),  # 对比度
    iaa.Affine(scale={"x": (0.9, 1.0), "y": (0.9, 1.0)}, rotate=(-180, 180)),  # 仿射变换
    iaa.GaussianBlur(sigma=(0, 3.0)),  # 高斯模糊
    iaa.AdditiveGaussianNoise(scale=(0, 0.05*255)),  # 高斯噪声
    iaa.Add((-50, 50), per_channel=0.5),# 亮度变化
], random_order=True))`
训练模型样本在线增强一般选择什么呢？感觉现在这种效果不是很明显？

**Comment by wang-zhix** [comment]
基本就这些了，你可以运行tool/image_aug.py文件，来查看一下增强后的效果，然后调整调整增强参数。

**Comment by Adorablepet** [comment]
> 基本就这些了，你可以运行tool/image_aug.py文件，来查看一下增强后的效果，然后调整调整增强参数。

我试了下人眼都分不清，是不是参数设置有问题？你能给些参考吗？谢谢

**Comment by wang-zhix** [comment]
![augmented_image](https://github.com/user-attachments/assets/b09c4c71-0482-4253-b65d-e6920ca603e3)
```
aug_seq = sometimes(iaa.Sequential([
    iaa.LinearContrast((0.8, 1.2)), # 增强或减弱图像的对比度
    iaa.Affine(scale={"x": (0.8, 1.2), "y": (0.8, 1.2)}, rotate=(-180, 180), ), # 仿射变换 缩放和旋转
    iaa.GaussianBlur(sigma=(0.1, 0.8)),  # 添加高斯模糊，sigma 参数控制模糊程度
    iaa.AdditiveGaussianNoise(scale=(0, 0.05 * 255)),  # 添加高斯噪声，scale 参数控制噪声强度
    iaa.Multiply((0.8, 1.2)),  # 调整图像的亮度
    iaa.PiecewiseAffine(scale=(0.01, 0.05)), # 分段仿射变换，随机扭曲图像的局部区域
], random_order=True,))

```

**Comment by Adorablepet** [comment]
这些是你训练时候用的增强方式吗？我用生成工具生成了10W+的假印章用作者默认的增强方式训练基础模型，验证集可以达到93%左右，然后用假数据训练的模型作为预训练模型去微调真实样本，样本增强方式用你提供的，但是验证集只有70%左右。是不是还有其他超参数要调整呢?lr为1e-4，epoch为100。还请兄弟指点下。@wang-zhix

**Comment by Adorablepet** [comment]
> 其他的参数没有什么特别的调整，主要还是数据集影响大。 是不是生成的假印章和真样本差距太大，93和70差的挺多。试着调整一下假样本的生成工具尽量相似一点。 另外假样本在生成点吧，10W可不够。
> 
> 还有一个增强颜色的，就是红和蓝互换，因为有时候有蓝色的章。

假样本生成工具用的是[https://github.com/wang-zhix/seal_generate](url)。只不过企业名称我用的是正常的，加了许多背景图，没有加纹理图，没有借助作者的随机组词。假样本生成的一般还是很清晰的，除了加了高斯模糊，只是真实的会有点不清晰。那假样本如何生成与真实的相似呢？

**Comment by wang-zhix** [comment]
这你只能自己尝试了，我这也没特别好的方法了。
如果是不清晰的话，你可以尝试把图像尺寸缩小，然后再给他放大（可以用不同的插值算法尝试），这也是一种模糊化的方法。
另外我觉得在制作假样本的时候只是使用真实的名称是不够的（但是未验证）。

**Comment by Adorablepet** [comment]
> 这你只能自己尝试了，我这也没特别好的方法了。 如果是不清晰的话，你可以尝试把图像尺寸缩小，然后再给他放大（可以用不同的插值算法尝试），这也是一种模糊化的方法。 另外我觉得在制作假样本的时候只是使用真实的名称是不够的（但是未验证）。

**Comment by Adorablepet** [comment]
> 这你只能自己尝试了，我这也没特别好的方法了。 如果是不清晰的话，你可以尝试把图像尺寸缩小，然后再给他放大（可以用不同的插值算法尝试），这也是一种模糊化的方法。 另外我觉得在制作假样本的时候只是使用真实的名称是不够的（但是未验证）。

你有么有遇到多卡训练速度并没有比单卡快多少，有时候反而也慢？把假印章与真印章一起训练和借助于作为提供的预训练模型训练一个基于假印章的基础模型，然后去微调真实样本？这区别大吗？还有一个关于epoch的问题，一般训练多少呢，我看80的时候都接近0.0001。你能提供一个训练日志看下吗。

**Comment by wang-zhix** [comment]
设置dataloader_num_workers试试，看看是不是数据加载太慢了。
区别大不大你得自己试试。我倾向于既用预训练，也用真假数据一起训练。
epoch搞大点让他跑呗，最后挑一个best不就好了，训练日志没有了。
