### ISSUE TITLE
测试权重链接失效

### ISSUE THREAD

**Issue by TongHengcheng** [Gmgge/TrOCR-Seal-Recognition#7]
你好，感谢你的项目分享。你实现的印章识别的方式对我们很有启发。我们想实验模型的识别效果，但发现权重的链接过期了，可以重新上传一份吗？谢谢。
![image](https://github.com/Gmgge/TrOCR-Seal-Recognition/assets/35362026/93137da0-699a-4ac1-81ff-6851df457fcf)

**Comment by colaman111** [comment]
> 你好，感谢你的项目分享。你实现的印章识别的方式对我们很有启发。我们想实验模型的识别效果，但发现权重的链接过期了，可以重新上传一份吗？谢谢。 ![image](https://user-images.githubusercontent.com/35362026/278231578-93137da0-699a-4ac1-81ff-6851df457fcf.png)

同求一份链接，感谢！

**Comment by Gmgge** [comment]
好的，我更新下模型链接。
如果有任何使用反馈，欢迎提出。
