### ISSUE TITLE
印章数据集已过期

### ISSUE THREAD

**Issue by wibin86** [Gmgge/TrOCR-Seal-Recognition#8]
你好，百度网盘分享的印章数据集已过期，能否再分享一下，或者将数据集上传到github，谢谢

**Comment by liushuchun** [comment]
同需要。

**Comment by Gmgge** [comment]
你好，网盘分享的是模型权重，已经更新链接。

由于真实印章数据的缺少，当前无法达到公开分享的程度，为了能够进一步优化印章识别的表现，当前数据分享策略为被共享人需要提供真实印章数据才可拥有整体印章数据共享的权限。

如果有需要共享的真实印章图像， 我这边可以协助提取建印章区域标签与印章识别标签，以构建完善的数据集。
